apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook 
  namespace: argocd
spec:
  project: default
  source:
    path: . 
    repoURL: https://github.com/TomerBahar22/ArgoStudy.git
    helm:
      releaseName: guestbook
  destination:
      server: "https://kubernetes.default.svc"
      namespace: default
