apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: {{ Values.replicas }}
  revisionHistoryLimit: {{ Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: {{ Values.containers.image }}
          name: guestbook-ui
          ports:
            - containerPort: {{ Values.containerPort }}
