apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: guestbook-ui
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
